In [1]:
import numpy as np

In [2]:
np.random.rand(10)

array([0.23688649, 0.48045658, 0.77554222, 0.07424074, 0.17480501,
       0.60620127, 0.91477009, 0.56389807, 0.08069873, 0.59940419])

In [4]:
foo = np.random.rand(4,4)
foo


array([[0.94411836, 0.69082899, 0.92450109, 0.1053159 ],
       [0.29639869, 0.62422352, 0.12502638, 0.23359153],
       [0.18641781, 0.53338411, 0.41390394, 0.29129862],
       [0.85501441, 0.90495889, 0.17615347, 0.4693181 ]])

In [11]:
foo.reshape(16,1)

array([[0.94411836],
       [0.69082899],
       [0.92450109],
       [0.1053159 ],
       [0.29639869],
       [0.62422352],
       [0.12502638],
       [0.23359153],
       [0.18641781],
       [0.53338411],
       [0.41390394],
       [0.29129862],
       [0.85501441],
       [0.90495889],
       [0.17615347],
       [0.4693181 ]])

In [12]:
foo.dtype

dtype('float64')